export const CURRENCIES = [
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    symbol: "د.إ",
    position: "right",
  },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", position: "left" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", position: "right" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", position: "right" },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    symbol: "ƒ",
    position: "left",
  },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", position: "left" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", position: "left" },
  { code: "AUD", name: "Australian Dollar", symbol: "$", position: "left" },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", position: "left" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", position: "right" },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
    position: "right",
  },
  { code: "BBD", name: "Barbadian Dollar", symbol: "$", position: "left" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", position: "left" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", position: "right" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", position: "right" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", position: "right" },
  { code: "BMD", name: "Bermudan Dollar", symbol: "$", position: "left" },
  { code: "BND", name: "Brunei Dollar", symbol: "$", position: "left" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", position: "left" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", position: "left" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "$", position: "left" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", position: "left" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", position: "left" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", position: "right" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", position: "left" },
  { code: "CAD", name: "Canadian Dollar", symbol: "$", position: "left" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", position: "right" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr", position: "left" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", position: "left" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", position: "left" },
  { code: "COP", name: "Colombian Peso", symbol: "$", position: "left" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", position: "left" },
  { code: "CUP", name: "Cuban Peso", symbol: "$", position: "left" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", position: "left" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", position: "right" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", position: "right" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", position: "right" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", position: "left" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", position: "right" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", position: "left" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", position: "left" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", position: "left" },
  { code: "EUR", name: "Euro", symbol: "€", position: "right" },
  { code: "FJD", name: "Fijian Dollar", symbol: "$", position: "left" },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    symbol: "£",
    position: "left",
  },
  { code: "GBP", name: "British Pound", symbol: "£", position: "left" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", position: "right" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", position: "left" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", position: "left" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", position: "left" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", position: "right" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", position: "left" },
  { code: "GYD", name: "Guyanaese Dollar", symbol: "$", position: "left" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "$", position: "left" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", position: "left" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", position: "right" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", position: "left" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", position: "right" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", position: "left" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", position: "left" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", position: "left" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", position: "right" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", position: "right" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", position: "right" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", position: "left" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", position: "right" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", position: "left" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", position: "left" },
  { code: "KGS", name: "Kyrgystani Som", symbol: "с", position: "right" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", position: "right" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", position: "right" },
  { code: "KPW", name: "North Korean Won", symbol: "₩", position: "left" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", position: "left" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", position: "right" },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "$", position: "left" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", position: "left" },
  { code: "LAK", name: "Laotian Kip", symbol: "₭", position: "left" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", position: "right" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", position: "left" },
  { code: "LRD", name: "Liberian Dollar", symbol: "$", position: "left" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", position: "left" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", position: "right" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", position: "right" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", position: "right" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", position: "left" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", position: "right" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", position: "left" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", position: "left" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", position: "left" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", position: "right" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", position: "left" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", position: "left" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", position: "left" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", position: "left" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", position: "left" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", position: "left" },
  { code: "NAD", name: "Namibian Dollar", symbol: "$", position: "left" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", position: "left" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", position: "left" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", position: "right" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", position: "left" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "$", position: "left" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", position: "right" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", position: "left" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/.", position: "left" },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    symbol: "K",
    position: "left",
  },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", position: "left" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", position: "left" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", position: "right" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", position: "left" },
  { code: "QAR", name: "Qatari Rial", symbol: "ر.ق", position: "right" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", position: "right" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин.", position: "right" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", position: "right" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", position: "right" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", position: "right" },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "$",
    position: "left",
  },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", position: "left" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", position: "right" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", position: "right" },
  { code: "SGD", name: "Singapore Dollar", symbol: "$", position: "left" },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", position: "left" },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", position: "left" },
  { code: "SOS", name: "Somali Shilling", symbol: "S", position: "left" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", position: "left" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", position: "left" },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    position: "right",
  },
  { code: "SYP", name: "Syrian Pound", symbol: "£", position: "left" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", position: "left" },
  { code: "THB", name: "Thai Baht", symbol: "฿", position: "left" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", position: "right" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", position: "right" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", position: "right" },
  { code: "TOP", name: "Tongan Pa'anga", symbol: "T$", position: "left" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", position: "left" },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    position: "left",
  },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", position: "left" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", position: "left" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", position: "right" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", position: "left" },
  { code: "USD", name: "United States Dollar", symbol: "$", position: "left" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", position: "left" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "лв", position: "right" },
  {
    code: "VES",
    name: "Venezuelan Bolívar Soberano",
    symbol: "Bs.S.",
    position: "left",
  },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", position: "right" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", position: "right" },
  { code: "WST", name: "Samoan Tala", symbol: "T", position: "left" },
  { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA", position: "right" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "$", position: "left" },
  { code: "XOF", name: "CFA Franc BCEAO", symbol: "CFA", position: "right" },
  { code: "XPF", name: "CFP Franc", symbol: "₣", position: "right" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", position: "right" },
  { code: "ZAR", name: "South African Rand", symbol: "R", position: "left" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", position: "left" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", position: "left" },
];
